/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wardView;

import models.Model;
import models.ModelSingleton;
import utility.Patient;
import utility.PatientData;
import utility.RandomData;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author samdavies
 */
public class WardCellJPanel extends javax.swing.JPanel {

    private Patient patient;
    private Timer timer;
    private int timerSeconds;
    public int nurseScore = 0;

    /**
     * Creates new form WardCellJPanel
     */
    public WardCellJPanel() {
        initComponents();
        //set timer
        timerSeconds = 0;
        if (timer == null) {
            timer = new Timer(100, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // do it every 1 second
                    Calendar cal = Calendar.getInstance();
                    cal.getTime();
                    SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss");
                    // do it every 5 seconds
                    if (timerSeconds % 5 == 0) {
                        //generate random value
                        int br = RandomData.generateReading(Model.RESPIRATORY_RATE);
                        int spo2 = RandomData.generateReading(Model.SPO2);
                        float temp = RandomData.generateReading(Model.TEMPERATURE);
                        int systolic = RandomData.generateReading(Model.SYSTOLIC);
                        int hr = RandomData.generateReading(Model.HEART_RATE);

                        PatientData patientData = new PatientData(br, spo2, temp, systolic, hr);
                        int score = patientData.getScore();
                        setScore(score);
                        setNurseScore(score + nurseScore);
                    }
                    timerSeconds++;
                }
            });
        }

        if (!timer.isRunning()) {
            timer.start();
        }
    }

    /**
     * Set the score colour and number in the view
     */
    public void setScore(int score) {
        Color red = new Color(250, 85, 65);;
        Color green = new Color(175, 250, 65);
        Color yellow = new Color(250, 175, 65);

        if(0 <= score && score <= 1){
            colourSquare.setBackground(green);
        }else if(2 <= score && score <= 3){
            colourSquare.setBackground(yellow);
        }else if(4 <= score){
            colourSquare.setBackground(red);
        }
    }

    public void setNurseScore(int score) {
        if(0 <= score && score <= 1){
            statusText.setText("<html>OK<html>");
        }else if(2 <= score && score <= 3){
            statusText.setText("<html>Continue routine observation</html>");
        }else if(4 <= score && score <= 5){
            statusText.setText("<html>Involve the nurse-in-charge immediately</html>");
        }else if(6 <= score){
            statusText.setText("<html>Call the registrar for immediate review</html>");
        }
    }

    public void setPatient(Patient patient){
        this.patient = patient;
        this.setPatientFields();
    }

    private void setPatientFields() {
        patientNameField.setText(patient.getFistName() + " " + patient.getLastName());
        wardNumField.setText("W001");
        bedNumField.setText(Integer.toString(patient.getBedNumber()));
        dobField.setText(patient.getDOB());
        genderField.setText(patient.getGender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientNameField = new javax.swing.JLabel();
        wardNumField = new javax.swing.JLabel();
        bedNumField = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        genderField = new javax.swing.JLabel();
        dobField = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        colourSquare = new javax.swing.JPanel();
        nurseRating = new javax.swing.JComboBox<>();
        statusText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(65, 65, 65));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        patientNameField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        patientNameField.setForeground(new java.awt.Color(242, 242, 242));
        patientNameField.setText("jLabel");

        wardNumField.setForeground(new java.awt.Color(242, 242, 242));
        wardNumField.setText("jLabel");

        bedNumField.setForeground(new java.awt.Color(242, 242, 242));
        bedNumField.setText("jLabel");

        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("DoB:");

        jLabel1.setForeground(new java.awt.Color(242, 242, 242));

        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("WARD:");

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("BED:");

        genderField.setForeground(new java.awt.Color(242, 242, 242));
        genderField.setText("jLabel");

        dobField.setForeground(new java.awt.Color(242, 242, 242));
        dobField.setText("jLabel");

        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("GENDER:");

        colourSquare.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout colourSquareLayout = new javax.swing.GroupLayout(colourSquare);
        colourSquare.setLayout(colourSquareLayout);
        colourSquareLayout.setHorizontalGroup(
            colourSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        colourSquareLayout.setVerticalGroup(
            colourSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        nurseRating.setBackground(new java.awt.Color(102, 102, 102));
        nurseRating.setForeground(new java.awt.Color(242, 242, 242));
        nurseRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alert", "Verbal", "Pain", "Unresponsive" }));
        nurseRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseRatingActionPerformed(evt);
            }
        });

        statusText.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        statusText.setForeground(new java.awt.Color(65, 175, 250));
        statusText.setText("Waiting for Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statusText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(colourSquare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dobField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bedNumField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(wardNumField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(nurseRating, 0, 170, Short.MAX_VALUE)
                            .addComponent(patientNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(wardNumField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(bedNumField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(genderField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nurseRating, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(colourSquare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusText)
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nurseRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseRatingActionPerformed
        // TODO add your handling code here:
        nurseScore = nurseRating.getSelectedIndex();
    }//GEN-LAST:event_nurseRatingActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        try {
            // try to get that ward
            WardJFrame ward = (WardJFrame) SwingUtilities.getWindowAncestor(this);
            ward.segueToPatient(this.patient);
        } catch ( final ClassCastException ex ) {
            System.out.println("Could not cast to WardJFrame");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bedNumField;
    private javax.swing.JPanel colourSquare;
    private javax.swing.JLabel dobField;
    private javax.swing.JLabel genderField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> nurseRating;
    private javax.swing.JLabel patientNameField;
    private javax.swing.JLabel statusText;
    private javax.swing.JLabel wardNumField;
    // End of variables declaration//GEN-END:variables
}
