/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientview;

import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;

/**
 *
 * @author samdavies
 */
public class FlatProgressBar extends javax.swing.JPanel {

    private Color barColour;
    private int percentage = 10;

    /**
     * Creates new form FlatProgressBar
     */
    public FlatProgressBar() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        Color grey = new Color(45, 45, 45);
        Color bar = barColour;
        this.drawRoundRect(g, this.getWidth(), grey);
        this.drawRoundRect(g, this.percentage * this.getWidth()/100, bar);
    }

    private void drawRoundRect(Graphics g, int width, Color colour){
        int height = this.getHeight();
        // Prepare a red rectangle
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D gb = bi.createGraphics();
        gb.setPaint(colour);
        gb.fillRect(0, 0, width, height);
        gb.dispose();

        // Set a rounded clipping region:
        RoundRectangle2D r = new RoundRectangle2D.Float(0, 0, width, height, 10, 10);
        g.setClip(r);

        // Draw the rectangle (and see whether it has round corners)
        g.drawImage(bi, 0, 0, null);
    }

    public void setBarColour(Color barColour) {
        this.barColour = barColour;
    }

    public void setPercentage(int percentage) {
        System.out.println(percentage);
        this.percentage = Math.max(percentage, 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
