/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package patientview;

import models.Model;
import models.ModelSingleton;
import utility.Patient;
import utility.PatientData;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.lang.reflect.Array;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Map;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

import utility.RandomData;
import wardView.WardJFrame;

/**
 *
 * @author Qi Zhou
 */
public class PatientJFrame extends javax.swing.JFrame {

    private Timer timer;
    private int timerSeconds;

    private Model model = ModelSingleton.getInstance();

    /**
     * Creates new form PatientJFrame
     */
    public PatientJFrame() throws IOException {
        initComponents();
        //set window in the center of the screen
        //Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        //Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;
        //Move the window
        this.setLocation(x, y);

        // set the initial patient
        this.setPatientFields();

        //set focus on exit button
        jButton_exit.requestFocus();
        //set timer
        timerSeconds = 0;
        if (timer == null) {
            timer = new Timer(100, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // do it every 1 second
                    Calendar cal = Calendar.getInstance();
                    cal.getTime();
                    SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd HH:mm:ss");
                    jLabel_systemTime.setText(sdf.format(cal.getTime()));
                    // do it every 5 seconds
                    if (timerSeconds % 5 == 0) {
                        String key = Integer.toString((timerSeconds % 3600) + 5);
                        displayData(model.getSelectedPatient().data.get(key));
                    }
                    timerSeconds++;
                }
            });
        }

        if (!timer.isRunning()) {
            timer.start();
        }
    }

    public void setPatientFields() {
        Patient patient = model.getSelectedPatient();

        patientNameField.setText(patient.getFistName() + " " + patient.getLastName());
        wardNumField.setText("W001");
        bedNumField.setText(Integer.toString(patient.getBedNumber()));
        dobField.setText(patient.getDOB());
        genderField.setText(patient.getGender());
    }

    private void displayData(PatientData patientData) {
        // breathing
        breathingField.setText(Integer.toString(patientData.getBreathing()));
        Color red = new Color(250, 85, 65);
        this.breathingBar.setBarColour(red);
        this.breathingBar.setPercentage((int) (100*patientData.getBreathing()/45.0));

        // oxygen
        oxygenField.setText(Integer.toString(patientData.getOxygen()));
        Color blue = new Color(65, 175, 250);
        this.oxygenBar.setBarColour(blue);
        this.oxygenBar.setPercentage((int) (100*patientData.getOxygen()/105.0));

        // temperature
        temperatureField.setText(String.format("%.02f", patientData.getTemperature()));
        Color yellow = new Color(250, 175, 65);
        this.temperatureBar.setBarColour(yellow);
        this.temperatureBar.setPercentage((int) (100*patientData.getTemperature()/45.0));

        // blood
        bloodPressureField.setText(Integer.toString(patientData.getBloodPressure()));
        Color green = new Color(175, 250, 65);
        this.bloodBar.setBarColour(green);
        this.bloodBar.setPercentage((int) (100*patientData.getBloodPressure()/210.0));

        // heart
        heartRateField.setText(Integer.toString(patientData.getHeartRate()));
        Color orange = new Color(175, 65, 250);
        this.heartBar.setBarColour(orange);
        this.heartBar.setPercentage((int) (100*patientData.getHeartRate()/170.0));

        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel_readings = new javax.swing.JPanel();
        oxygenField = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        temperatureField = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bloodPressureField = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        heartRateField = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        breathingLabel = new javax.swing.JLabel();
        breathingField = new javax.swing.JLabel();
        breathingBar = new patientview.FlatProgressBar();
        oxygenBar = new patientview.FlatProgressBar();
        bloodBar = new patientview.FlatProgressBar();
        temperatureBar = new patientview.FlatProgressBar();
        heartBar = new patientview.FlatProgressBar();
        jPanel_buttons = new javax.swing.JPanel();
        jButton_exit = new javax.swing.JButton();
        jButton_changeView = new javax.swing.JButton();
        jPanel_title = new javax.swing.JPanel();
        jLabel_systemTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patientNameField = new javax.swing.JLabel();
        wardNumField = new javax.swing.JLabel();
        bedNumField = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dobField = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        genderField = new javax.swing.JLabel();
        nextPatient = new javax.swing.JButton();
        previousPatient = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(65, 65, 65));

        jPanel1.setBackground(new java.awt.Color(65, 65, 65));

        jPanel_readings.setBackground(new java.awt.Color(65, 65, 65));
        jPanel_readings.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        oxygenField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        oxygenField.setForeground(new java.awt.Color(242, 242, 242));
        oxygenField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        oxygenField.setText("oxygenField");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Oxygen saturation");

        temperatureField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        temperatureField.setForeground(new java.awt.Color(242, 242, 242));
        temperatureField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        temperatureField.setText("temperatureField");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Temperature");

        bloodPressureField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bloodPressureField.setForeground(new java.awt.Color(242, 242, 242));
        bloodPressureField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bloodPressureField.setText("bloodPressureField");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 242, 242));
        jLabel10.setText("Systolic blood pressure:");

        heartRateField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        heartRateField.setForeground(new java.awt.Color(242, 242, 242));
        heartRateField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        heartRateField.setText("heartRateField");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(242, 242, 242));
        jLabel11.setText("Heart rate");

        breathingLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        breathingLabel.setForeground(new java.awt.Color(242, 242, 242));
        breathingLabel.setText("Respiratory rate");

        breathingField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        breathingField.setForeground(new java.awt.Color(242, 242, 242));
        breathingField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        breathingField.setText("breathingField");

        org.jdesktop.layout.GroupLayout breathingBarLayout = new org.jdesktop.layout.GroupLayout(breathingBar);
        breathingBar.setLayout(breathingBarLayout);
        breathingBarLayout.setHorizontalGroup(
            breathingBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        breathingBarLayout.setVerticalGroup(
            breathingBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 9, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout oxygenBarLayout = new org.jdesktop.layout.GroupLayout(oxygenBar);
        oxygenBar.setLayout(oxygenBarLayout);
        oxygenBarLayout.setHorizontalGroup(
            oxygenBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        oxygenBarLayout.setVerticalGroup(
            oxygenBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 9, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout bloodBarLayout = new org.jdesktop.layout.GroupLayout(bloodBar);
        bloodBar.setLayout(bloodBarLayout);
        bloodBarLayout.setHorizontalGroup(
            bloodBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        bloodBarLayout.setVerticalGroup(
            bloodBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 9, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout temperatureBarLayout = new org.jdesktop.layout.GroupLayout(temperatureBar);
        temperatureBar.setLayout(temperatureBarLayout);
        temperatureBarLayout.setHorizontalGroup(
            temperatureBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        temperatureBarLayout.setVerticalGroup(
            temperatureBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 9, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout heartBarLayout = new org.jdesktop.layout.GroupLayout(heartBar);
        heartBar.setLayout(heartBarLayout);
        heartBarLayout.setHorizontalGroup(
            heartBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        heartBarLayout.setVerticalGroup(
            heartBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 9, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jPanel_readingsLayout = new org.jdesktop.layout.GroupLayout(jPanel_readings);
        jPanel_readings.setLayout(jPanel_readingsLayout);
        jPanel_readingsLayout.setHorizontalGroup(
            jPanel_readingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_readingsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel_readingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel_readingsLayout.createSequentialGroup()
                        .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(heartRateField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(oxygenBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(temperatureBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel_readingsLayout.createSequentialGroup()
                        .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(temperatureField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(bloodBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel_readingsLayout.createSequentialGroup()
                        .add(jLabel10)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(bloodPressureField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(heartBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel_readingsLayout.createSequentialGroup()
                        .add(jPanel_readingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(breathingLabel)
                            .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel_readingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, breathingField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, oxygenField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(breathingBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_readingsLayout.setVerticalGroup(
            jPanel_readingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_readingsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel_readingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(breathingLabel)
                    .add(breathingField))
                .add(4, 4, 4)
                .add(breathingBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel_readingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(oxygenField))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(oxygenBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel_readingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(temperatureField))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(temperatureBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel_readingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(bloodPressureField))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bloodBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel_readingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(heartRateField))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(heartBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_buttons.setBackground(new java.awt.Color(65, 65, 65));

        jButton_exit.setText("Exit");
        jButton_exit.setBorderPainted(false);
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });

        jButton_changeView.setText("Ward View");
        jButton_changeView.setBorderPainted(false);
        jButton_changeView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_changeViewActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel_buttonsLayout = new org.jdesktop.layout.GroupLayout(jPanel_buttons);
        jPanel_buttons.setLayout(jPanel_buttonsLayout);
        jPanel_buttonsLayout.setHorizontalGroup(
            jPanel_buttonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_buttonsLayout.createSequentialGroup()
                .add(jButton_changeView, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton_exit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 242, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel_buttonsLayout.setVerticalGroup(
            jPanel_buttonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_buttonsLayout.createSequentialGroup()
                .add(jPanel_buttonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButton_changeView, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton_exit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 12, Short.MAX_VALUE))
        );

        jPanel_title.setBackground(new java.awt.Color(65, 65, 65));
        jPanel_title.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_systemTime.setForeground(new java.awt.Color(242, 242, 242));
        jLabel_systemTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_systemTime.setText("TIME");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("WARD NUMBER:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("BED NUMBER:");

        patientNameField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        patientNameField.setForeground(new java.awt.Color(65, 175, 250));
        patientNameField.setText("jLabel");

        wardNumField.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        wardNumField.setForeground(new java.awt.Color(242, 242, 242));
        wardNumField.setText("jLabel");

        bedNumField.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        bedNumField.setForeground(new java.awt.Color(242, 242, 242));
        bedNumField.setText("jLabel");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("DoB:");

        dobField.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        dobField.setForeground(new java.awt.Color(242, 242, 242));
        dobField.setText("jLabel");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("GENDER:");

        genderField.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        genderField.setForeground(new java.awt.Color(242, 242, 242));
        genderField.setText("jLabel");

        org.jdesktop.layout.GroupLayout jPanel_titleLayout = new org.jdesktop.layout.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel_titleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(patientNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel_systemTime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel_titleLayout.createSequentialGroup()
                        .add(jPanel_titleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jLabel4)
                            .add(jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel_titleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(wardNumField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(bedNumField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(dobField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(genderField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel_systemTime)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(patientNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel_titleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(wardNumField))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel_titleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(bedNumField))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel_titleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(dobField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel_titleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(genderField))
                .addContainerGap())
        );

        nextPatient.setBackground(new java.awt.Color(65, 65, 65));
        nextPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_002@2x.png"))); // NOI18N
        nextPatient.setBorderPainted(false);
        nextPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPatientActionPerformed(evt);
            }
        });

        previousPatient.setBackground(new java.awt.Color(65, 65, 65));
        previousPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_001@2x.png"))); // NOI18N
        previousPatient.setBorderPainted(false);
        previousPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousPatientActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jPanel_buttons, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jPanel_title, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel_readings, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(previousPatient, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(36, 36, 36)
                            .add(nextPatient, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel_title, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel_readings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(67, 67, 67)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(previousPatient, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(nextPatient, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel_buttons, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousPatientActionPerformed
        // TODO add your handling code here:
        // add 5
        model.selectedPatient += 5;
        // modulus 6
        model.selectedPatient %= 6;
        this.setPatientFields();
    }//GEN-LAST:event_previousPatientActionPerformed

    private void nextPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPatientActionPerformed
        // TODO add your handling code here:
        // add 1
        model.selectedPatient ++;
        // modulus 6
        model.selectedPatient %= 6;
        this.setPatientFields();
    }//GEN-LAST:event_nextPatientActionPerformed

    private void jButton_changeViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_changeViewActionPerformed
        // TODO add your handling code here:
        //open the Ward-View
        WardJFrame wardframe = new WardJFrame();
        wardframe.setVisible(true);
        //dispose current window
        this.dispose();
    }//GEN-LAST:event_jButton_changeViewActionPerformed

    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PatientJFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(PatientJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bedNumField;
    private patientview.FlatProgressBar bloodBar;
    private javax.swing.JLabel bloodPressureField;
    private patientview.FlatProgressBar breathingBar;
    private javax.swing.JLabel breathingField;
    private javax.swing.JLabel breathingLabel;
    private javax.swing.JLabel dobField;
    private javax.swing.JLabel genderField;
    private patientview.FlatProgressBar heartBar;
    private javax.swing.JLabel heartRateField;
    private javax.swing.JButton jButton_changeView;
    private javax.swing.JButton jButton_exit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_systemTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_buttons;
    private javax.swing.JPanel jPanel_readings;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JButton nextPatient;
    private patientview.FlatProgressBar oxygenBar;
    private javax.swing.JLabel oxygenField;
    private javax.swing.JLabel patientNameField;
    private javax.swing.JButton previousPatient;
    private patientview.FlatProgressBar temperatureBar;
    private javax.swing.JLabel temperatureField;
    private javax.swing.JLabel wardNumField;
    // End of variables declaration//GEN-END:variables
}
